#!/bin/bash

read old new branch
commitmessage="$(git show --oneline $new | sed -n '1p' | cut -d ' ' -f 2-)"
filename="$(grep -P '(?<=#publish: ).*' <<< $commitmessage)"

if [ $? != 0 ]; then
	exit 0
fi

echo "publishing!"

PATH="$HOME"

git-show "$new:$filename.tex" > "$PATH"
cd "$PATH"
make full f="$filename" | at now
