#!/bin/bash

read old new branch
commitmessage="$(git show --oneline $new | sed -n '1p' | cut -d ' ' -f 2-)"
filename="$(grep -oP '(?<=#publish: ).*' <<< $commitmessage)"

if [ $? != 0 ]; then
	exit 0
fi

echo "publishing!"

# This should somehow be auto modified.
# Probably by copying this template and editing this file from the makefile
DIR="$HOME/lecture"
SUBDIR=`pwd | awk -F '/' '{print $NF}' | awk -F '.' '{print $1}'`

mkdir "$DIR/$SUBDIR"

git show "$new:$filename.tex" > "$DIR/$SUBDIR/$filename.tex"
cd "$DIR"
make file="$filename" path="$SUBDIR"
