#!/bin/bash

read old new branch
commitmessage="$(git show --oneline $new | sed -n '1p' | cut -d ' ' -f 2-)"
filename="$(grep -oP '(?<=#publish: ).*' <<< $commitmessage)"

if [ $? != 0 ]; then
	exit 0
fi

echo "publishing!"

# TODO change this depending on how the makefile was run
SUBDIR=`pwd | awk -F '/' '{print $NF}'`
DIR="$HOME/lecture/"

mkdir "$DIR/$SUBDIR"

git show "$new:$filename.tex" > "$DIR/$SUBDIR/$filename.tex"
cd "$DIR"
make file="$filename" path="$SUBDIR"
