#!/bin/bash

# usage:
#	./get-keywords <filename>
# <filename> should be the path to where the tex file, note hovever
# that it shouldn't have a extension.
# Make sure that a propperly written log-file with the name
# <filename>.log is present

# Currently this requires the jar file for publishing to the sql,
# as well as the log file, to be placed in the same directory as
# this script. Thish should be changed.

rawfile=$1

grep -e '\.(log|tex)$' <<< "$rawfile" \
	&& filename=${rawfile::-4} \
	|| filename=$rawfile

# Just piping to read aparently doesn't work with read...
read database user password <<< `cut -d = -f 2 database.ini | tr '\n' ' '`

iconv -s -f iso-8859-1 -t utf-8 "$filename.log" \
	| grep -oP '\d \[(keyword|course|title)\]:.*' \
	| sort -t ' ' -hk 1 \
	| cut -d ' ' -f 3- \
	| cat <(echo "$filename") - \
   	| java -jar database-deploy.jar \
		--database $database \
		--user $user \
		--password $password
